### ISSUE TITLE
在vue项目里使用，报错

### ISSUE THREAD

**Issue by peade** [spritejs/sprite-extend-shapes#6]
在运行时，console里打印出来了了两段错误信息

> [Vue warn]: Error in mounted hook: "TypeError: Class constructor BaseSprite cannot be invoked without 'new'"

>  Class constructor BaseSprite cannot be invoked without 'new'

在项目编译的时候，报了这个错误

>  warning  in ./src/components/Test.vue?vue&type=script&lang=js&
"export 'Circle' (imported as 'Spritejs') was not found in 'spritejs'

js代码部分，这个是写在vue组件里用的。

```
import * as Spritejs from 'spritejs'
  import Shapes from 'sprite-extend-shapes'

  Spritejs.use(Shapes)
  const {Circle} = Spritejs
  export default {
    name: 'Test',
    data() {
      return {}
    },
    computed: {},
    watch: {},
    created() {
    },
    mounted() {
      const scene = new Spritejs.Scene('#game', {
        viewport: ['auto', 'auto'], resolution: [375, 667],
        stickMode: 'width'
      })
      const layer = scene.layer()
      const circle = new Circle()
      circle.attr({
        radius: 30,
        lineWidth: 5,
        color: 'red',
        anchor: [0.5, 0.5],
        font: '44px Arial',
        pos: [0, 0],
      })
      layer.append(circle)
    }
  }
```

**Comment by justemit** [comment]
试下改成 `import * as Spritejs from 'spritejs/dist/spritejs.min.js'`

**Comment by peade** [comment]
> 试下改成 `import * as Spritejs from 'spritejs/dist/spritejs.min.js'`。
> 
> 此外， 在 markdown 中写代码块前后都要用 3 个反引号。举个栗子：
> 
> ```js
> import * as Spritejs from 'spritejs'
> import Shapes from 'sprite-extend-shapes'
> ```
> 
> 上面这种代码块的写法是：
> 
> ```js
> import * as Spritejs from 'spritejs'
> import Shapes from 'sprite-extend-shapes'
> ```

谢谢，能解决了。
你这个也提醒了我了。
除了这种引入方式外，
在webpack里，配置
```
 resolve: {
    alias: {
      spritejs: 'spritejs/dist/spritejs.js'
    }
  },
```
